version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "walker84837"
    labels:
      - "dependencies"
      - "gradle"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"

    security-updates:
      check-in: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

# Control number of open PRs (default is 5)
open-pull-requests-limit: 3
